web:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./httpdocs/:/var/www/html
    - ./config/vhost.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  build: docker-images/php5.6
  volumes:
    - ./config/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./httpdocs/:/var/www/html
  links:
    - "mysql:mysql"
    - "mongo:mongo"
mysql:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - ./data/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=symfony_db
    - MYSQL_USER=symfony_u
    - MYSQL_PASSWORD=SomeRandomPWD
mongo:
  image: mongo:2.4.14
  volumes:
    - ./data/mongo:/data/db
  ports:
    - "27017:27017"